package com.api.ejemplo.apidocker.model;

import java.util.Date;
import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;

@DynamoDBDocument
public class Transaccion {

    @DynamoDBAutoGeneratedKey
    //@DynamoDBHashKey(attributeName = "transactionId")
    @DynamoDBAttribute(attributeName = "transactionId")
    private String transactionId;
    
    @DynamoDBAttribute(attributeName = "fondoId")
    private String fondoId;

    @DynamoDBAttribute(attributeName = "tipo")
    private String tipo;

    @DynamoDBAttribute(attributeName = "monto")
    private double monto;

    @DynamoDBAttribute(attributeName = "fecha")
    private Date fecha; // Debe ser un String formateado como ISO 8601

    // Getters y Setters
    public Transaccion() {
        this.transactionId = UUID.randomUUID().toString();
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getFondoId() {
        return fondoId;
    }

    public void setFondoId(String fondoId) {
        this.fondoId = fondoId;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public double getMonto() {
        return monto;
    }

    public void setMonto(double monto) {
        this.monto = monto;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}
